### PR TITLE
Add Remove-PlexCollection

### PR DESCRIPTION
**Pull request by solid03**

### CODE REVIEW

**Comment by robinmalik** [comment]
Thanks for the contribution @solid03 - I'll try and get around to testing this tonight!

**Comment by robinmalik** [comment]
@solid03 The example given (`Get-PlexCollection | Where-object {[int]$_.childCount -lt 5} | Select-Object -ExpandProperty ratingKey | Remove-PlexCollection`) doesn't work because `Get-PlexCollection` doesn't return objects without either providing a collection id, or a library id. 

~~Also, pipelining doesn't work because `Remove-PlexCollection` expects an id property but Plex being annoying as it is, doesn't have that on a collection object.~~ I take that back - was importing new code from the wrong source directory. pipelining attempts something but I'm getting unauthorised.

**Comment by robinmalik** [comment]
@solid03 Ok, another issue my side. Merged into main and published. Thanks again!

**Comment by solid03** [comment]
Thanks for your time!

**Pull request merged**
